//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResource() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSite.Resources.MainResource", typeof(MainResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AI Integration &amp; Development.
        /// </summary>
        public static string AI_API {
            get {
                return ResourceManager.GetString("AI_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;p style=&quot;margin-bottom: 20px;&quot;&gt;
        ///  We bring Artificial Intelligence into your software!
        ///&lt;/p&gt;
        ///
        ///&lt;p style=&quot;margin-bottom: 20px;&quot;&gt;
        ///   We build applications that learn, adapt, and deliver personalized user experiences.&lt;br&gt;
        ///   Our custom solutions combine traditional technologies and AI to improve efficiency, simplify interactions, and enhance digital content.
        ///&lt;/p&gt;
        ///&lt;p style=&quot;margin-bottom: 20px;&quot;&gt;
        /// &lt;strong&gt;Curious about what we can build for you?&lt;/strong&gt;&lt;br&gt;
        ///    Get in touch and request a personalized  [stringa troncata]&quot;;.
        /// </summary>
        public static string AI_API_Description {
            get {
                return ResourceManager.GetString("AI_API_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AI Content Creation.
        /// </summary>
        public static string AI_Content_title {
            get {
                return ResourceManager.GetString("AI_Content_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;p style=&quot;margin-bottom: 20px;&quot;&gt;
        ///  We harness the power of Artificial Intelligence to create high-quality multimedia content tailored to your communication and digital needs.
        ///&lt;/p&gt;
        ///
        ///&lt;p style=&quot;margin-bottom: 20px;&quot;&gt;
        ///  Whether it&apos;s engaging videos, audio content, or dynamic integrations, we leverage advanced AI technologies to speed up production and deliver professional results quickly.
        ///&lt;/p&gt;
        ///
        ///&lt;p style=&quot;margin-bottom: 20px;&quot;&gt;
        ///  Contact us for a DEMO — we’ll show you how we can enhance your brand with  [stringa troncata]&quot;;.
        /// </summary>
        public static string AI_ContentDescription {
            get {
                return ResourceManager.GetString("AI_ContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gralcall is Graldev&apos;s answer to the Augmented Reality requests of our customers and partners.
        ///Gralcall is software that can be adapted down to the smallest detail. &lt;/br&gt;
        ///Try it now and then visit the dedicated page for more information.
        /// </summary>
        public static string ARAppDevelopmentDescription {
            get {
                return ResourceManager.GetString("ARAppDevelopmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contact Us / Join Us.
        /// </summary>
        public static string ContactUs_JoinUs {
            get {
                return ResourceManager.GetString("ContactUs_JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cross platform app.
        /// </summary>
        public static string CrossPlatformApp {
            get {
                return ResourceManager.GetString("CrossPlatformApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a We integrate the systems with the ad hoc creation of native and web based apps for smartphones, tablets, wearables and for all &quot;smart&quot; devices..
        /// </summary>
        public static string CrossPlatformAppDescription {
            get {
                return ResourceManager.GetString("CrossPlatformAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;em&gt;Customers and Partners&lt;/em&gt;.
        /// </summary>
        public static string CustomersAndPartners {
            get {
                return ResourceManager.GetString("CustomersAndPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Customers and Partners.
        /// </summary>
        public static string CustomersPartners {
            get {
                return ResourceManager.GetString("CustomersPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Digital support.
        /// </summary>
        public static string DigitalSupport {
            get {
                return ResourceManager.GetString("DigitalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Discover.
        /// </summary>
        public static string DiscoverGeordie {
            get {
                return ResourceManager.GetString("DiscoverGeordie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Take a look.
        /// </summary>
        public static string DiscoverGTransport {
            get {
                return ResourceManager.GetString("DiscoverGTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E-Mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Find out more.
        /// </summary>
        public static string FindOutMore {
            get {
                return ResourceManager.GetString("FindOutMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Geordie is our solution to help you manage your online sales. &lt;/br&gt;
        ///Access your stores in an organized and simple way with this highly customizable tool based on your needs.
        /// </summary>
        public static string GeordieDescription {
            get {
                return ResourceManager.GetString("GeordieDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Graldev&apos;s Mission is to accompany the customer on the path between an idea and its realization, providing adequate support before, during and after development..
        /// </summary>
        public static string GraldevMission {
            get {
                return ResourceManager.GetString("GraldevMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IT Consulting.
        /// </summary>
        public static string ITConsulting {
            get {
                return ResourceManager.GetString("ITConsulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you have a project you want to realize but don&apos;t know where to start?&lt;br/&gt;
        ///Contact us!
        ///&lt;br/&gt;
        ///We will help you find the most suitable solution to realize your idea..
        /// </summary>
        public static string ITConsultingDescription {
            get {
                return ResourceManager.GetString("ITConsultingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ludirex (beta) is the social platform conceived and created, in collaboration with Ludirex Srl, as a meeting point for players looking for companions or teams to play online. &lt;/br&gt; Register now!.
        /// </summary>
        public static string LudirexDescription {
            get {
                return ResourceManager.GetString("LudirexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The message has been sent, thank you!.
        /// </summary>
        public static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name/Company (optional).
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a We are looking for a &lt;b&gt;Software Developer&lt;/b&gt; who has the following characteristics: &lt;/br&gt; &lt;/br&gt;
        ///Knowledge of one or more of the following &lt;b&gt;programming languages&lt;/b&gt; &lt;/br&gt;
        ///-&lt;b&gt;C#&lt;/b&gt;&lt;/br&gt;
        ///-&lt;b&gt;Java&lt;/b&gt;&lt;/br&gt;
        ///-&lt;b&gt;Angular&lt;/b&gt;&lt;/br&gt;
        ///Knowledge of &lt;b&gt;Web framework&lt;/b&gt; based on Javascript&lt;/br&gt;
        ///Knowledge of &lt;b&gt;Web API REST&lt;/b&gt;&lt;/br&gt;
        ///Services Experience with &lt;b&gt;SQL Server and MySQL&lt;/b&gt;&lt;/br&gt;
        ///Relational databases Knowledge and use of &lt;b&gt;GIT&lt;/b&gt;&lt;/br&gt;
        ///Propensity to &lt;b&gt;Team work&lt;/b&gt;&lt;/br&gt;&lt;/br&gt;
        ///For your applicati [stringa troncata]&quot;;.
        /// </summary>
        public static string NewProfessionalsDescriptions {
            get {
                return ResourceManager.GetString("NewProfessionalsDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a We are looking for &lt;em&gt;New professionals&lt;/em&gt; to be included in our staff!.
        /// </summary>
        public static string NewProfessionalsTitle {
            get {
                return ResourceManager.GetString("NewProfessionalsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New technologies.
        /// </summary>
        public static string NewTech {
            get {
                return ResourceManager.GetString("NewTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The best way to understand how we can help you is ... to see and experience what we have already done and to know what our customers think!.
        /// </summary>
        public static string OurProjectDescription {
            get {
                return ResourceManager.GetString("OurProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Take a look at our latest &lt;em&gt;Software Projects&lt;/em&gt;.
        /// </summary>
        public static string OurProjectTitle {
            get {
                return ResourceManager.GetString("OurProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Our services.
        /// </summary>
        public static string OurServices {
            get {
                return ResourceManager.GetString("OurServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parcor is the web app that we are creating for the Segni Project, a project relating to the world of intercompany nurseries and of which Graldev is a technological partner.
        ///An application that will allow users to always be informed about news and to interact with other users, organizations and companies involved..
        /// </summary>
        public static string ParcorDescription {
            get {
                return ResourceManager.GetString("ParcorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Phone (optional).
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read more.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send Request.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sign Up!.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Software assistance and support.
        /// </summary>
        public static string SoftwareAssistance {
            get {
                return ResourceManager.GetString("SoftwareAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Software and Web services.
        /// </summary>
        public static string SofwareAndWebServices {
            get {
                return ResourceManager.GetString("SofwareAndWebServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a We design and create complete enterprise software solutions. We create automatic services and processes for all types of communication..
        /// </summary>
        public static string SofwareAndWebServicesDescription {
            get {
                return ResourceManager.GetString("SofwareAndWebServicesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Complete solutions analysis and development.
        /// </summary>
        public static string SolutionsAnalysisAndDevelopment {
            get {
                return ResourceManager.GetString("SolutionsAnalysisAndDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Soon available.
        /// </summary>
        public static string SoonAvailable {
            get {
                return ResourceManager.GetString("SoonAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Support and advice.
        /// </summary>
        public static string SupportAndAdvice {
            get {
                return ResourceManager.GetString("SupportAndAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a We provide consultancy on software architecture to realize the idea and assistance in the use of our products with the necessary maintenance..
        /// </summary>
        public static string SupportAndAdviceDescription {
            get {
                return ResourceManager.GetString("SupportAndAdviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you have a project to carry out? &lt;/br&gt; Do you want to work with us? &lt;/br&gt; Send a request!.
        /// </summary>
        public static string TellUsAboutYourIdea {
            get {
                return ResourceManager.GetString("TellUsAboutYourIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Try it!.
        /// </summary>
        public static string TryIt {
            get {
                return ResourceManager.GetString("TryIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Useful links.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visit the site.
        /// </summary>
        public static string VisiteTheSite {
            get {
                return ResourceManager.GetString("VisiteTheSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Latest Projects.
        /// </summary>
        public static string WhatDoWeDo {
            get {
                return ResourceManager.GetString("WhatDoWeDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ours are years of very rapid evolution of technologies related to communication. Smartphones, tablets, wearables and dedicated hardware are objects we use on a daily basis, and large-scale digital information has undeniably filled our lives.&lt;/br&gt; We at Graldev are right there, in the midst of the whirling, very fast, heterogeneous flow of data and we make our contribution by developing software, services, apps and media.&lt;/br&gt; Our work team brings together the twenty-year experience of those who have experie [stringa troncata]&quot;;.
        /// </summary>
        public static string WhoWeAreDescription {
            get {
                return ResourceManager.GetString("WhoWeAreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;em&gt;Who we are&lt;/em&gt;.
        /// </summary>
        public static string WhoWeAreTitle {
            get {
                return ResourceManager.GetString("WhoWeAreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Our work team brings together the twenty-year experience of those who have experienced the countless technological changes firsthand with the enthusiasm and desire for innovation of our youngest collaborators..
        /// </summary>
        public static string WorkTeamDescription {
            get {
                return ResourceManager.GetString("WorkTeamDescription", resourceCulture);
            }
        }
    }
}
